### GET ACCESS TOKEN
POST http://localhost:5000/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&scope=secret_api.access offline_access&client_id=apiClient&client_secret=apiSecret&username=apiUser&password=apiUserPassword

### ACCESS API #1
GET http://localhost:5001/api/identity
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjNFNDRBODVDRTg0NjRGQzlDNkI1NzIxMTk0MjhBRkVFIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2MDk0NzY0MTQsImV4cCI6MTYwOTQ3NjQ3NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoic2VjcmV0X2FwaSIsImNsaWVudF9pZCI6ImFwaUNsaWVudCIsInN1YiI6IjRBMkVDMDY1LTBBMDctNEQxNy1CQTcxLUE5QUEwNDA5NTlGNCIsImF1dGhfdGltZSI6MTYwOTQ3NjQxNCwiaWRwIjoibG9jYWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsIkRlcGFydG1lbnQiOiJTaGFuZ2hhaSIsImp0aSI6IkEyNTc2REUzMzAzMTg0RjREQzExRUQ5MTdBMUE0QkEyIiwiaWF0IjoxNjA5NDc2NDE0LCJzY29wZSI6WyJzZWNyZXRfYXBpLmFjY2VzcyIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJwd2QiXX0.neJNSMI7i8JjttxNnm_YhloHkjiNrfw87jUyOhWo3lu_aUbasX8Lj7FvDSkjK1GuB0D555ZzTDiCGp-y4DCQ_L6UrbITotlZjeA891r4OVla7K1DUjor66pMSM-Ww9u6APpJWLFgEF6wv_gF3-Rlg07Qx7eanf9TnN5XUBvDDPqo-jRlyUAc7-A5_cl9bWlrvAkESGwDNZr5BJQU2e9BZh_6O2CuKgu2bJ4MrNmaspLYaLgxu0Oa-TIXcXgcuJlo9cYs0ZxC8y3XrUmzFA8zJ4P-iwhBU2w8FFlZiQCWZV7uXlyYK6rOChMa63wOKZTM1yK_9cMl2YzuNnxwLDUDyg

### GET ACCESS TOKEN WITH REFRESH TOKEN
POST http://localhost:5000/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&client_id=apiClient&client_secret=apiSecret&refresh_token=EE008F6FC1EBF00C8E5B24CEFED5FA2A8CBD3A5A31AA0033CCDCE1F0C82386BC

### ACCESS API #2 with Adminstrator
GET http://localhost:5002/home/GetData?username=apiUser&password=apiUserPassword

### ACCESS API #2 with Guest
GET http://localhost:5002/home/GetData?username=apiUserGuest&password=apiUserPassword

