### GET ACCESS TOKEN
POST http://localhost:5000/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&scope=secret_api.access&client_id=apiClient&client_secret=apiSecret&username=apiUser&password=apiUserPassword

### ACCESS API #1
GET http://localhost:5001/api/identity
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjNFNDRBODVDRTg0NjRGQzlDNkI1NzIxMTk0MjhBRkVFIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2MDkyOTg3ODAsImV4cCI6MTYwOTMwMjM4MCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoic2VjcmV0X2FwaSIsImNsaWVudF9pZCI6ImFwaUNsaWVudCIsInN1YiI6IjRBMkVDMDY1LTBBMDctNEQxNy1CQTcxLUE5QUEwNDA5NTlGNCIsImF1dGhfdGltZSI6MTYwOTI5ODc4MCwiaWRwIjoibG9jYWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImp0aSI6IjE3OTIxODc0M0EyOTUxQzRCN0I5MTQwOTlDMTlFMUZCIiwiaWF0IjoxNjA5Mjk4NzgwLCJzY29wZSI6WyJzZWNyZXRfYXBpLmFjY2VzcyJdLCJhbXIiOlsicHdkIl19.iom_hTekUA0cG2P7mTT_mEFx46McnH7phPejd_R3QzD4-EgYbqQmfZnT1hfbFL8PSMsDHgyysPqYyD8uYaCj3-9H6BzLhRQ6KkfJj_rsxnU98o_zb15UySjdSKSxDXjKr1tf3PPnqrBeDpFSKNJTrzz2j5AinKlzBUPvWRL-8E6m0pZKHtILYTLZ2rUDaHrzGWxJJsu_dZoMLiojo0T78Q8jXzb0NoOFSG98Zxlu2rb26LEGrVevSsAplRlc0TFXGG8XtzJBSq6hn1Mo3yWCKaDiBp3_6U4duqvm4GL0-GfmuMRvsAbFdAuJ-LZisQ0blgweHqKB9EGpvMt8VUBdDA

### ACCESS API #2 with Adminstrator
GET http://localhost:5002/home/GetData?username=apiUser&password=apiUserPassword

### ACCESS API #2 with Guest
GET http://localhost:5002/home/GetData?username=apiUserGuest&password=apiUserPassword

