POST http://localhost:5100/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=api1.read&client_id=ApiTwo&client_secret=APISecretKey

###
GET http://localhost:5001/home/secret
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkUxODkxRTY3MjRFQ0NGREMzMTIxNTBCOUQ1MDhBNkVGIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2MDkyMTkwNDMsImV4cCI6MTYwOTIyMjY0MywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTAwIiwiYXVkIjoiQXBpT25lIiwiY2xpZW50X2lkIjoiQXBpVHdvIiwianRpIjoiMjVFQjI2Q0NBODM4RkJFQjY0Mjg0MTI0NjYyMzk0OTYiLCJpYXQiOjE2MDkyMTkwNDMsInNjb3BlIjpbImFwaTEucmVhZCJdfQ.MziWNpG_OPUCpkApnLgNwI2yqa3X_KHWqPrETVyNOjUm8YShHefczJQ27_tv2rZy5WSf_voBdCVvHi45Nq7MfTDk_P_m68tvYHI1p7DQ0fvezW0pJevthFWlfQVAv0P_rd7I2mUREXnkqlsyZT_biJGwjJ_XhoU4lgFrgdUxl5h6pim2R-NfVFPy36tTGTpvb63pc-NFGfvljhRhS5apvb_25yr9T2nv4YlcSHZyETjRVt5J-BNqo-cItEUnp3gK3p1tISXN05Zh8rGdK34AX9_jgnQJMJC64KtKP1kB0MjkmKwXZ36QyHW6zlJXuHI8GlpVgPSG1nocG3CBdTfaiQ

###
GET http://localhost:5002/process/clientcredentialtest
