### GET ACCESS TOKEN
POST http://localhost:5000/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=secret_api.access&client_id=apiClient&client_secret=apiSecret

### ACCESS API #1
GET http://localhost:5001/api/identity
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjNFNDRBODVDRTg0NjRGQzlDNkI1NzIxMTk0MjhBRkVFIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2MDkyOTgwNDEsImV4cCI6MTYwOTMwMTY0MSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoic2VjcmV0X2FwaSIsImNsaWVudF9pZCI6ImFwaUNsaWVudCIsInN1YiI6IjRBMkVDMDY1LTBBMDctNEQxNy1CQTcxLUE5QUEwNDA5NTlGNCIsImF1dGhfdGltZSI6MTYwOTI5ODA0MCwiaWRwIjoibG9jYWwiLCJqdGkiOiI2MzBFOTZDNzNDMTBCNjU4NDQzOUYxNjcwOUZCMDdBRSIsImlhdCI6MTYwOTI5ODA0MCwic2NvcGUiOlsic2VjcmV0X2FwaS5hY2Nlc3MiXSwiYW1yIjpbInB3ZCJdfQ.Clhw1YR5ano-uUqusu6vPi7HSNmawzprdgxEAPGCtHQPupeacY4BkNr4WqkdOPP9pkhu4gskxzFk2DZgOWMfGfYnx4euCYSJj31rILShtsftuEFfBdLTQXwci00WZsCALY43VJ5w06h-Z_bpG45B1MPYqOZE2l-Pp4OZiJyBvFEmYxEQ7UFMcy2-YKkNMngiTZR2pRZVQr_Ix9cBuEsCw6g-JvwzbhwbHGdUcRUBSVL-eaMklp4qVfFYv_h-vg6TEIXgwP5h3yur7x6BpcLFEy7E1Iu44EKOGWV2aPZ0SM-eeeRzcvuRl4_Vg_xSDiQuSvn9YAoQTxckLfePCfMYuw

### ACCESS API #2
GET http://localhost:5002/home/GetData

